### PR TITLE
#770 remove sidebar margin in iframe

### LINKED ISSUE #770: cozy topbar padding regressions
Image

### PR DESCRIPTION
**Pull request by lethemanh**
### Related to:

https://github.com/linagora/twake-calendar-frontend/issues/770

## Summary by CodeRabbit

* **Bug Fixes**
  * Adjusted sidebar display spacing for embedded calendar contexts.

### CODE REVIEW

**Comment by Arsnael** [comment]
Docker image published for this PR: linagora/twake-calendar-web:pr-794

**Review by Eriikah — APPROVED** [review]

**Review by chibenwa — APPROVED** [review]

File: src/components/Calendar/Sidebar/DesktopSidebar.tsx [hunk 1]
```diff
@@ -30,7 +30,7 @@ export function DesktopSidebar({
           paddingLeft: 3,
           paddingRight: 2,
           width: '270px',
-          marginTop: '70px'
+          marginTop: isIframe ? 0 : '70px'
```
Comment (Crash--) [inline src/components/Calendar/Sidebar/DesktopSidebar.tsx:33]: OK for a quick fix, but I'm wondering why this component needs to know about this isIframe. It should be handled differently. I don't know how because I'm don't have a good understanding of the codebase, but if you need to have a talk on this subject, let's discuss. 

Do we have this issue also for Tablet & Mobile Component?
